### ISSUE TITLE
Failure to reproduce the results of the paper

### ISSUE THREAD

**Issue by ykch75** [nicopietroni/parafashion#2]
Thank you for making your code and data public!

I'm struggling to reproduce the results in the paper. My environment is Windows 10 WSL.
For example, I ran the program with data of Fig. 1.
- `./parafashion Figures_Pattern_Making/Figures/fig_1_teaser/flawless.obj`
- Then press 'Batch Process' button.

I attached the screenshot after the above process.
It looks very different from Fig. 1.
How can I get the similar pattern as Fig. 1?

![image](https://github.com/nicopietroni/parafashion/assets/57245761/15bbca83-c77d-40e4-970a-0abd894c75cc)

**Comment by CorentinDumery** [comment]
Hello ykch75, thanks for your interest!

So the algorithm that adds cuts is greedy and doesn't have knowledge of where tailors typically like to have the cuts. So, as illustrated in Figure 18 of the paper, in our UI you can add some constraints and the algorithm will introduce cuts that match your strokes.

You can add those strokes by holding the spacebar pressed, then clicking on the mesh and drawing a stroke. Sorry if this isn't clear on the UI, we still haven't taken the time to polish it...

Most of the figures are produced without any additional stroke, except (if I remember correctly) Fig 1/2. To get the results from the teaser, try something like this:
![image](https://github.com/nicopietroni/parafashion/assets/43251496/88ba8bc2-7e3c-411d-84fa-c69165221ca4)

Let me know if this helps!
Corentin

**Comment by ykch75** [comment]
Thank you for your prompt reply!

I put the strokes as you said, but it didn't look the same.

![image](https://github.com/nicopietroni/parafashion/assets/57245761/bc6a9888-416d-409f-a832-8c414f1fdd84)

By 'Remove Along Symmetry' button, it becomes closer to the figure in the paper but it still has notable differences.

![image](https://github.com/nicopietroni/parafashion/assets/57245761/5515bbe3-a557-40aa-83a2-239b6d4c9c39)

Especially, I would like to know how to make the partial cuts / darts as shown in the blue rectangle below.
My strokes by holding the spacebar always make connections to patch boundaries with causing complete cuts. They cannot stop in the middle.
<img width="299" alt="image" src="https://github.com/nicopietroni/parafashion/assets/57245761/5991430b-8690-4f01-86e7-564130602fff">

> Most of the figures are produced without any additional stroke, except (if I remember correctly) Fig 1/2.

I tried other figures, but they did not look the same.

For example, I tried Fig19(C=8, s_max=0.05). I regard C and s_max in the paper as 'Max Corners' and 'Max Tension' in the UI.

![image](https://github.com/nicopietroni/parafashion/assets/57245761/274e74ad-e8ae-4351-98ba-afd1df8efeb0)

I would appreceate it if you could respond.

**Comment by CorentinDumery** [comment]
For Fig 1, there's a checkbox "Allow darts" that is not checked in your screenshots. Also, darts are only useful in areas with high curvature, and your horizontal stroke is lower than mine, this makes it less likely to introduce a dart because there is less curvature there. You can remove a stroke by double clicking on it.

For Fig 19, 1) you should have darts enabled and 2) use 'Remove Along Symmetry' after batch process. 

You might not get exactly the same result. Ultimately, this is a greedy algorithm, so a small change in the inputs/code can lead to different results. But using input strokes and parameters, you should always be able to generate something satisfying.

**Comment by CorentinDumery** [comment]
Dear @ykch75, I hope this helped. If that's fine, I will close this issue. Don't hesitate to contact me if I can help you further :)

Corentin

**Comment by ykch75** [comment]
> this is a greedy algorithm, so a small change in the inputs/code can lead to different results. But using input strokes and parameters, you should always be able to generate something satisfying.

Thanks for tips. I'll look further into it and test with other combination of paramaters.

After all, thank you very much for all your kind help! Keep up with your amazing work!
