### ISSUE TITLE
Core dumped issue

### ISSUE THREAD

**Issue by vikm2o** [nicopietroni/parafashion#3]
@nicopietroni 
I always get Aborted (core dumped) when I run parafashion command

OS : 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Error:
GLOBAL fontscaling=1
Loading Deformed Mesh flawless.obj
Loading Reference Mesh flawless.obj
Loaded 20343 faces of deformed mesh 
Loaded 10292 vertices of deformed mesh  
Loaded 20343 faces of reference mesh 
Loaded 10292 vertices of reference mesh  
Aborted (core dumped)

I ran the command on Figures_Pattern_Making/Figures/fig_1_tease/flawless.obj

I also ran on a 3D scan of person wearing a dress. I get the same issue.

**Comment by CorentinDumery** [comment]
Hi @vikm2o, 

I just ran the app on that same input, and did not encounter any issue. It was also used by someone else in another github issue. Here is the command:  `./parafashion ../data/Figures_Pattern_Making/Figures/fig_1_tease/flawless.obj`

Can you please share the exact command you used, if it is different?

Regarding your 3D scan, I cannot say anything without additional information, but check that you are giving correct input arguments. If your scan also includes the person wearing the dress however, this would be a problem.

**Comment by vikm2o** [comment]
@CorentinDumery Yes the scan I used included a person wearing the dress.

When I ran `parafashion Figures_Pattern_Making/Figures/fig_1_tease/flawless.obj` It seems to work. I can see the mesh.
![Screenshot from 2023-07-17 10-45-44](https://github.com/nicopietroni/parafashion/assets/114598851/d9d54544-515b-4896-84c2-722ec4068589)

But when I run `Save Data` the svg and the png generated seem odd. Are they sewing patterns? Is there a sample 3d that I can use to test.

[flawless_UV.txt](https://github.com/nicopietroni/parafashion/files/12065745/flawless_UV.txt)
![flawless_patch](https://github.com/nicopietroni/parafashion/assets/114598851/e980d666-7caa-405b-8fbf-d20c310389ec)
[flawless_patch.txt](https://github.com/nicopietroni/parafashion/files/12065746/flawless_patch.txt)
![flawless_patch](https://github.com/nicopietroni/parafashion/assets/114598851/645301e4-4106-49ab-b422-3da248aa862a)


Is there documentation on how to use the software?

Also Is there a possibility of using the command on a scan of a person/mannequin wearing a dress? I would like to compare the generated sewing patterns with the actuals.

**Comment by CorentinDumery** [comment]
Did you compute results before attempting to save them? This can be done
using the button "Batch run". You can also add user inputs by holding the
space bar and click.

No there is no documention, it's been on my todo list for a while. We
should at least simplify the UI and make the Batch run button bigger...
This is related to issue #1.

Regarding your last point, if it's disconnected from the piece of garment
you can easily remove the person using software like blender, for example.
Our app takes garment meshes as input.

Hope that helps, don't hesitate to ask again if I can help you figure out
what the UI does. And I'll try to improve it someday 😊

**Comment by vikm2o** [comment]
@CorentinDumery Thanks a lot. I can now see 2d patterns correctly!

**Comment by CorentinDumery** [comment]
No problem, don't hesitate to ask again if something is unclear!
Corentin
